### ISSUE TITLE
Code Error？

### ISSUE THREAD

**Issue by root4399** [sihohan/FuSAGNet#1]
Hello,
I ran into the following issues when I tried to execute the code:

FuSAGNet\models\graph_layer.py", line 57, in forward
    edge_index, _ = add_self_loops(edge_index, num_nodes=x[1].size(self.node_dim))
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)

Is this a bug in the code？Thanks a lot for your answer in advance.

**Comment by seansihohan** [comment]
Hi,

Please check if PyTorch Geometric 1.5.0 is installed, as the function arguments might have been changed for newer versions.

Thanks
