### ISSUE TITLE
Visualization of figure from the paper

### ISSUE THREAD

**Issue by root4399** [sihohan/FuSAGNet#2]
Hi,

I am really struggling to generate a graph based layout of my data, similar to your figure 3 and figure 4. Can you please provide the following:

1 .A simple python file that could help in visualization.
2. Instructions on how, where and at what stage to run it. Basically a readme instructions.

Thanks

**Comment by seansihohan** [comment]
Hi,

I don't have the code for visualizing figures 3 and 4 right now, but you can simply implement them by using scikit-learn's TSNE function with the sensor embeddings (fig. 3) and latent vectors (fig. 4) as respective inputs following model training.

Thanks

**Comment by root4399** [comment]
Hi,


Thanks for your quick reply, I will try to solve the problem.&nbsp;But I encountered another problem: the reproduction results of the experiment were quite different from those in the paper. Can you provide some experimental hyperparameters to help me better reproduce the experimental results?


Thanks




382486783
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sihohan/FuSAGNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月25日(星期五) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sihohan/FuSAGNet] Visualization of figure from the paper (Issue #2)





 
Hi,
 
I don't have the code for visualizing figures 3 and 4 right now, but you can simply implement them by using scikit-learn's TSNE function with the sensor embeddings (fig. 3) and latent vectors (fig. 4) as respective inputs following model training.
 
Thanks

**Comment by seansihohan** [comment]
Hi @root4399 , sorry for the late reply.

The performance discrepancy may have resulted from the randomness when initializing weights.
I suggest you try evaluating using different random seeds, as they may affect the prediction performance.

Thanks.
