### ISSUE TITLE
process Np

### ISSUE THREAD

**Issue by fffii** [sihohan/FuSAGNet#4]
Hi,
can I ask you a question? How to choose the process where  Np is the number of processes. Because I have my own dataset, it seems that different dataset correspond to different processes.

Have a nice day! Thanks~~
<img width="653" alt="截屏2024-04-01 10 31 11" src="https://github.com/sihohan/FuSAGNet/assets/115461655/9aff7834-df27-4934-89df-492f8eae1f49">

**Comment by seansihohan** [comment]
Hi @fffii ,

I can further assist you, should you provide a more detailed explanation of your dataset.
Generally, P1, P2, and so on, constitute a larger group of "processes" comprising different numbers of sensors (or features or columns in typical tabular data).
If you can somehow group your columns based on their characteristics, these groups can be referred to as P1, P2, ..., and you can adjust `process_dict` accordingly.

Thanks.

**Comment by fffii** [comment]
Thanks! ### 

> Hi @fffii ,
> 
> I can further assist you, should you provide a more detailed explanation of your dataset. Generally, P1, P2, and so on, constitute a larger group of "processes" comprising different numbers of sensors (or features or columns in typical tabular data). If you can somehow group your columns based on their characteristics, these groups can be referred to as P1, P2, ..., and you can adjust `process_dict` accordingly.
> 
> Thanks.
