### ISSUE TITLE
The paper results are not reproducible, so don't be fooled

### ISSUE THREAD

**Issue by zdc132** [sihohan/FuSAGNet#6]

**Comment by seansihohan** [comment]
Hi @zdc132,
Sorry for the late reply, I've been caught up in work.

As for the issues you raised in [#5](https://github.com/sihohan/FuSAGNet/issues/5), I hope you understand that the results may significantly vary depending on the random seed. This has also been mentioned many times on GDN's issues page (e.g., [here](https://github.com/d-ailin/GDN/issues/29) and [here](https://github.com/d-ailin/GDN/issues/17)), so you could first try to reproduce the results using only the GDN and add the elements from FuSAGNet from that once you get satisfactory results.
